import type { Metadata } from "next";
import { TopNav } from "@/components/Navigation";
import { TripProvider } from "@/context/TripContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import { AICopilot } from "@/components/AICopilot";

export const metadata: Metadata = {
  title: "WANDR - AI Travel Planner",
  description: "Generated by Wandr Multi-Agent System",
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body className="text-on-surface antialiased bg-background overflow-x-hidden" suppressHydrationWarning>
        <ClerkProvider>
          <Toaster position="bottom-right" toastOptions={{ style: { borderRadius: '12px', background: '#333', color: '#fff' } }} />
          <AuthProvider>
            <TripProvider>
              <TopNav />
              {/* Main Content */}
              <main className="min-h-screen">
                {children}
              </main>
              <AICopilot />
            </TripProvider>
          </AuthProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
